# Usamos Python oficial
FROM python:3.11-slim

# Carpeta de trabajo
WORKDIR /app

# Copiamos requirements (si tienes)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código
COPY . .

# Puerto que expondrá Flask
EXPOSE 5000

# Comando para arrancar Flask
CMD ["python", "main.py"]
